---
# Role tasks

- name: Setup filesystems
  filesystem:
    dev: >-
      {{ filesystem.dev
         | default(filesystem_fs_defaults.dev) }}
    force: >-
      {{ filesystem_fs_filesystem.force
         | default(filesystem_fs_defaults.force)
         | default(omit) }}
    fstype: >-
      {{ filesystem_fs_filesystem.fstype
         | default(filesystem_fs_defaults.fstype)
         | default(omit) }}
    opts: >-
      {{ filesystem_fs_filesystem.opts
         | default(filesystem_fs_defaults.opts)
         | default(omit) }}
    resizefs: >-
      {{ filesystem_fs_filesystem.resizefs
         | default(filesystem_fs_defaults.resizefs)
         | default(omit) }}
  loop: "{{ filesystem_fs_filesystems_to_manage }}"
  loop_control:
    loop_var: filesystem
    label: "{{ filesystem.dev }} / {{ filesystem.fstype }}"

  vars:
    filesystem_fs_filesystems_to_manage: >-
      {{ filesystem_fs
         + ((filesystem_fs_load_from_hostvars | bool)
          | ternary(filesystem_fs_hostvars | default([]) | flatten, [])) }}
  tags:
    - role::filesystem
